import { AthleteProfile } from '../core/models/user.model';

export const MOCK_ATHLETES: AthleteProfile[] = [
  {
    id: 'ath_001',
    email: 'lucas.martinez@mail.com',
    fullName: 'Lucas Martínez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    role: 'athlete',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    bio: 'Mediocampista creativo con visión de juego. Buscando oportunidades en primera división.',
    createdAt: new Date('2024-03-15'),
    level: 'semi-professional',
    position: 'Mediocampista',
    currentClub: 'Racing Club - Reserva',
    age: 22,
    height: 178,
    weight: 73,
  },
  {
    id: 'ath_002',
    email: 'sofia.gutierrez@mail.com',
    fullName: 'Sofía Gutiérrez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    role: 'athlete',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    bio: 'Jugadora de hockey sobre césped. Selección santafesina Sub-21.',
    createdAt: new Date('2024-01-10'),
    level: 'professional',
    position: 'Delantera',
    currentClub: 'Jockey Club Rosario',
    age: 20,
    height: 165,
    weight: 58,
  },
  {
    id: 'ath_003',
    email: 'matias.rodriguez@mail.com',
    fullName: 'Matías Rodríguez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Matias',
    role: 'athlete',
    discipline: 'running',
    location: 'Córdoba Capital, Córdoba',
    bio: 'Maratonista amateur, corredor de montaña. 3h15 en maratón.',
    createdAt: new Date('2024-05-20'),
    level: 'amateur',
    position: 'Fondista',
    currentClub: 'Córdoba Running Team',
    age: 34,
    height: 172,
    weight: 65,
  },
  {
    id: 'ath_004',
    email: 'valentina.lopez@mail.com',
    fullName: 'Valentina López',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina',
    role: 'athlete',
    discipline: 'swimming',
    location: 'San Isidro, Buenos Aires',
    bio: 'Nadadora de competición. Especialista en 200m libre y 400m combinados.',
    createdAt: new Date('2024-02-28'),
    level: 'professional',
    position: 'Libre / Combinados',
    currentClub: 'Club Atlético San Isidro',
    age: 19,
    height: 174,
    weight: 62,
  },
  {
    id: 'ath_005',
    email: 'nicolas.fernandez@mail.com',
    fullName: 'Nicolás Fernández',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nicolas',
    role: 'athlete',
    discipline: 'football',
    location: 'Liniers, Buenos Aires',
    bio: 'Lateral derecho con buena proyección ofensiva. Formado en Vélez.',
    createdAt: new Date('2024-04-12'),
    level: 'professional',
    position: 'Lateral Derecho',
    currentClub: 'Club Atlético Vélez Sarsfield',
    age: 24,
    height: 176,
    weight: 71,
  },
  {
    id: 'ath_006',
    email: 'franco.diaz@mail.com',
    fullName: 'Franco Díaz',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Franco',
    role: 'athlete',
    discipline: 'boxing',
    location: 'La Matanza, Buenos Aires',
    bio: 'Peso mediano. 12 peleas amateur, 9 victorias. Preparándome para el debut profesional.',
    createdAt: new Date('2024-06-01'),
    level: 'semi-professional',
    position: 'Peso Mediano',
    currentClub: 'Gimnasio Ringo Bonavena',
    age: 26,
    height: 180,
    weight: 75,
  },
  {
    id: 'ath_007',
    email: 'camila.herrera@mail.com',
    fullName: 'Camila Herrera',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Camila',
    role: 'athlete',
    discipline: 'basketball',
    location: 'Bahía Blanca, Buenos Aires',
    bio: 'Base con manejo de pelota y visión de pase. Liga Femenina de Básquet.',
    createdAt: new Date('2024-03-08'),
    level: 'professional',
    position: 'Base',
    currentClub: 'Bahía Basket Femenino',
    age: 23,
    height: 170,
    weight: 64,
  },
  {
    id: 'ath_008',
    email: 'tomas.acosta@mail.com',
    fullName: 'Tomás Acosta',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tomas',
    role: 'athlete',
    discipline: 'rugby',
    location: 'Tucumán, Tucumán',
    bio: 'Fullback con buena patada. Jugador del seleccionado tucumano.',
    createdAt: new Date('2024-07-15'),
    level: 'semi-professional',
    position: 'Fullback',
    currentClub: 'Tucumán Rugby Club',
    age: 27,
    height: 183,
    weight: 88,
  },
];
