import { Club } from '../core/models/club.model';

export const MOCK_CLUBS: Club[] = [
  {
    id: 'club_001',
    name: 'Racing Club',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    foundedYear: 1903,
    facilities: ['Estadio Presidente Perón', 'Predio Tita Mattiussi', 'Gimnasio cubierto', 'Cancha sintética', 'Departamento médico'],
    description: 'Club Atlético Racing Club, uno de los grandes del fútbol argentino. Formador de talentos con fuerte presencia en inferiores.',
    memberCount: 85000,
    colors: 'Celeste y Blanco',
    divisions: [
      {
        id: 'div_001',
        clubId: 'club_001',
        name: 'Primera División',
        category: 'Primera',
        playerIds: ['ath_005', 'ath_001'],
        staffIds: ['coach_003', 'hp_002', 'hp_001'],
      },
      {
        id: 'div_002',
        clubId: 'club_001',
        name: 'Reserva',
        category: 'Reserva',
        playerIds: ['ath_001'],
        staffIds: ['coach_001', 'hp_002', 'coach_004'],
      },
      {
        id: 'div_003',
        clubId: 'club_001',
        name: '5ta División',
        category: 'Sub-17',
        playerIds: [],
        staffIds: ['coach_001', 'hp_002', 'coach_004'],
      },
    ],
  },
  {
    id: 'club_002',
    name: 'Club Atlético Vélez Sarsfield',
    discipline: 'football',
    location: 'Liniers, Buenos Aires',
    foundedYear: 1910,
    facilities: ['Estadio José Amalfitani', 'Villa Olímpica', 'Cancha auxiliar', 'Centro de rehabilitación'],
    description: 'Reconocido por su cantera y la formación de jugadores de jerarquía internacional.',
    memberCount: 72000,
    colors: 'Azul y Blanco',
    divisions: [
      {
        id: 'div_004',
        clubId: 'club_002',
        name: 'Primera División',
        category: 'Primera',
        playerIds: ['ath_005'],
        staffIds: ['coach_003', 'hp_004'],
      },
      {
        id: 'div_005',
        clubId: 'club_002',
        name: 'Reserva',
        category: 'Reserva',
        playerIds: [],
        staffIds: ['coach_003'],
      },
    ],
  },
  {
    id: 'club_003',
    name: 'Jockey Club Rosario',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    foundedYear: 1901,
    facilities: ['Cancha de hockey sintética', 'Cancha auxiliar', 'Gimnasio', 'Vestuarios nuevos'],
    description: 'Club tradicional de Rosario con fuerte desarrollo en hockey femenino y masculino.',
    memberCount: 12000,
    colors: 'Azul y Rojo',
    divisions: [
      {
        id: 'div_006',
        clubId: 'club_003',
        name: 'Primera Damas',
        category: 'Primera',
        playerIds: ['ath_002'],
        staffIds: ['coach_002', 'hp_003'],
      },
      {
        id: 'div_007',
        clubId: 'club_003',
        name: 'Juveniles Damas',
        category: 'Sub-21',
        playerIds: ['ath_002'],
        staffIds: ['coach_002'],
      },
    ],
  },
  {
    id: 'club_004',
    name: 'Córdoba Running Team',
    discipline: 'running',
    location: 'Córdoba Capital, Córdoba',
    foundedYear: 2015,
    facilities: ['Pista atlética', 'Gimnasio funcional', 'Sala de stretching'],
    description: 'Equipo de running que compite en maratones y carreras de montaña a nivel nacional.',
    memberCount: 350,
    colors: 'Naranja y Negro',
    divisions: [
      {
        id: 'div_008',
        clubId: 'club_004',
        name: 'Grupo Competitivo',
        category: 'Elite',
        playerIds: ['ath_003'],
        staffIds: ['hp_003'],
      },
      {
        id: 'div_009',
        clubId: 'club_004',
        name: 'Grupo Recreativo',
        category: 'Amateur',
        playerIds: [],
        staffIds: [],
      },
    ],
  },
  {
    id: 'club_005',
    name: 'Bahía Basket',
    discipline: 'basketball',
    location: 'Bahía Blanca, Buenos Aires',
    foundedYear: 2010,
    facilities: ['Estadio Dow Center', 'Gimnasio de musculación', 'Cancha auxiliar'],
    description: 'Proyecto de básquet bahiense que compite en la Liga Nacional y forma jugadores para la selección.',
    memberCount: 5000,
    colors: 'Verde y Blanco',
    divisions: [
      {
        id: 'div_010',
        clubId: 'club_005',
        name: 'Liga Femenina',
        category: 'Primera',
        playerIds: ['ath_007'],
        staffIds: ['hp_005'],
      },
    ],
  },
];
