import { Conversation, Message, ServiceRequest, CalendarEvent } from '../core/models/communication.model';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_chat_001',
    participants: [
      { userId: 'ath_001', name: 'Lucas Martínez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
      { userId: 'hp_001', name: 'Dra. Martina Pérez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Martina' },
    ],
    lastMessage: 'Te paso el plan actualizado para esta semana.',
    lastMessageAt: '2024-08-05T10:30:00',
    unreadCount: 1,
    isGroup: false,
  },
  {
    id: 'conv_chat_002',
    participants: [
      { userId: 'ath_001', name: 'Lucas Martínez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
      { userId: 'hp_002', name: 'Roberto Silva', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto' },
    ],
    lastMessage: 'Mañana arrancamos con la rutina nueva. Llevá vendas de rodilla.',
    lastMessageAt: '2024-08-04T18:45:00',
    unreadCount: 0,
    isGroup: false,
  },
  {
    id: 'conv_chat_003',
    participants: [
      { userId: 'ath_001', name: 'Lucas Martínez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
      { userId: 'coach_001', name: 'Carlos Medina', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CarlosM' },
      { userId: 'hp_002', name: 'Roberto Silva', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto' },
      { userId: 'hp_001', name: 'Dra. Martina Pérez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Martina' },
    ],
    lastMessage: 'Confirmado el amistoso del sábado. Concentración a las 8am.',
    lastMessageAt: '2024-08-05T09:15:00',
    unreadCount: 3,
    isGroup: true,
    groupName: 'Reserva - Cuerpo Técnico',
  },
  {
    id: 'conv_chat_004',
    participants: [
      { userId: 'ath_002', name: 'Sofía Gutiérrez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia' },
      { userId: 'coach_002', name: 'María Sosa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MariaSosa' },
    ],
    lastMessage: 'Bien el entrenamiento de hoy. Seguí con los ejercicios de definición.',
    lastMessageAt: '2024-08-05T17:00:00',
    unreadCount: 0,
    isGroup: false,
  },
  {
    id: 'conv_chat_005',
    participants: [
      { userId: 'ath_003', name: 'Matías Rodríguez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Matias' },
      { userId: 'hp_003', name: 'Lic. Alejandra García Méndez', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandra' },
    ],
    lastMessage: 'La molestia en el tendón cedió. Podés retomar los fondos largos.',
    lastMessageAt: '2024-08-04T14:20:00',
    unreadCount: 0,
    isGroup: false,
  },
];

export const MOCK_MESSAGES: Message[] = [
  // Conversation 001 - Lucas & Nutri
  {
    id: 'msg_001',
    conversationId: 'conv_chat_001',
    senderId: 'hp_001',
    senderName: 'Dra. Martina Pérez',
    content: 'Hola Lucas, ¿cómo te sentiste con la dieta de la semana pasada?',
    timestamp: '2024-08-05T09:00:00',
    read: true,
  },
  {
    id: 'msg_002',
    conversationId: 'conv_chat_001',
    senderId: 'ath_001',
    senderName: 'Lucas Martínez',
    content: 'Bien doc! Me sentí con más energía en los entrenamientos. Pero me costó la cena post-entreno, llegaba sin hambre.',
    timestamp: '2024-08-05T09:15:00',
    read: true,
  },
  {
    id: 'msg_003',
    conversationId: 'conv_chat_001',
    senderId: 'hp_001',
    senderName: 'Dra. Martina Pérez',
    content: 'Perfecto, vamos a ajustar eso. Te paso el plan actualizado para esta semana.',
    timestamp: '2024-08-05T10:30:00',
    read: false,
  },
  // Conversation 002 - Lucas & PF
  {
    id: 'msg_004',
    conversationId: 'conv_chat_002',
    senderId: 'hp_002',
    senderName: 'Roberto Silva',
    content: 'Lucas, revisé tus números del GPS del último partido. Muy bien los metros de alta intensidad.',
    timestamp: '2024-08-04T17:30:00',
    read: true,
  },
  {
    id: 'msg_005',
    conversationId: 'conv_chat_002',
    senderId: 'ath_001',
    senderName: 'Lucas Martínez',
    content: 'Gracias profe! Sentí que mejoré bastante la resistencia al sprint.',
    timestamp: '2024-08-04T18:00:00',
    read: true,
  },
  {
    id: 'msg_006',
    conversationId: 'conv_chat_002',
    senderId: 'hp_002',
    senderName: 'Roberto Silva',
    content: 'Mañana arrancamos con la rutina nueva. Llevá vendas de rodilla.',
    timestamp: '2024-08-04T18:45:00',
    read: true,
  },
];

export const MOCK_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'sr_001',
    fromUserId: 'ath_006',
    fromUserName: 'Franco Díaz',
    toUserId: 'hp_001',
    toUserName: 'Dra. Martina Pérez',
    type: 'consultation',
    title: 'Consulta nutricional para corte de peso',
    description: 'Necesito un plan para bajar al peso mediano (72.5kg) para mi debut profesional en 6 semanas.',
    status: 'pending',
    amount: '$12.000',
    createdAt: '2024-08-05',
  },
  {
    id: 'sr_002',
    fromUserId: 'club_003',
    fromUserName: 'Jockey Club Rosario',
    toUserId: 'hp_003',
    toUserName: 'Lic. Alejandra García Méndez',
    type: 'hiring',
    title: 'Incorporación como Kinesióloga del plantel',
    description: 'Ofrecemos puesto part-time (L-M-V) para atender al plantel de hockey femenino.',
    status: 'pending',
    amount: '$220.000/mes',
    createdAt: '2024-08-03',
  },
  {
    id: 'sr_003',
    fromUserId: 'ath_003',
    fromUserName: 'Matías Rodríguez',
    toUserId: 'hp_003',
    toUserName: 'Lic. Alejandra García Méndez',
    type: 'consultation',
    title: 'Sesión de kinesiología - Tendón de Aquiles',
    description: 'Molestia en el tendón de Aquiles después de la última maratón. Necesito evaluación y plan de recuperación.',
    status: 'accepted',
    amount: '$8.000',
    createdAt: '2024-07-28',
  },
  {
    id: 'sr_004',
    fromUserId: 'club_001',
    fromUserName: 'Racing Club',
    toUserId: 'coach_001',
    toUserName: 'Carlos Medina',
    type: 'hiring',
    title: 'Renovación contrato DT 5ta División',
    description: 'Ofrecemos renovación por 1 año más como DT de la 5ta división con mejora salarial.',
    status: 'accepted',
    amount: '$500.000/mes',
    createdAt: '2024-07-15',
  },
  {
    id: 'sr_005',
    fromUserId: 'ath_001',
    fromUserName: 'Lucas Martínez',
    toUserId: 'hp_005',
    toUserName: 'Lic. Carolina Romero',
    type: 'consultation',
    title: 'Sesión de psicología deportiva',
    description: 'Quiero trabajar el manejo de presión antes de los partidos importantes. Me genera mucha ansiedad.',
    status: 'completed',
    amount: '$9.000',
    createdAt: '2024-07-20',
  },
];

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt_001',
    title: 'Entrenamiento - Reserva',
    description: 'Sesión de campo: posesión y finalización',
    date: '2024-08-06',
    time: '09:00',
    type: 'training',
    location: 'Predio Tita Mattiussi',
    participants: ['ath_001', 'coach_001', 'hp_002'],
  },
  {
    id: 'evt_002',
    title: 'Consulta Nutrición',
    description: 'Control semanal con Dra. Pérez',
    date: '2024-08-07',
    time: '10:00',
    type: 'consultation',
    location: 'Consultorio Caballito',
    participants: ['ath_001', 'hp_001'],
  },
  {
    id: 'evt_003',
    title: 'Partido vs Independiente (Reserva)',
    description: 'Fecha 15 - Torneo de Reserva AFA',
    date: '2024-08-10',
    time: '11:00',
    type: 'match',
    location: 'Estadio Libertadores de América',
    participants: ['ath_001', 'coach_001'],
  },
  {
    id: 'evt_004',
    title: 'Gimnasio - Tren inferior',
    description: 'Rutina de fuerza según plan de Roberto',
    date: '2024-08-06',
    time: '15:00',
    type: 'training',
    location: 'Gimnasio Predio Racing',
    participants: ['ath_001', 'hp_002'],
  },
  {
    id: 'evt_005',
    title: 'Control médico mensual',
    description: 'Apto físico y control de laboratorio',
    date: '2024-08-12',
    time: '08:30',
    type: 'medical',
    location: 'Departamento Médico Racing',
    participants: ['ath_001', 'hp_004'],
  },
  {
    id: 'evt_006',
    title: 'Entrenamiento Hockey - Primera',
    description: 'Trabajo táctico: jugadas preparadas',
    date: '2024-08-06',
    time: '17:00',
    type: 'training',
    location: 'Cancha sintética Jockey Club',
    participants: ['ath_002', 'coach_002'],
  },
  {
    id: 'evt_007',
    title: 'Maratón de Córdoba',
    description: 'Carrera 42k - Objetivo sub 3h10',
    date: '2024-08-18',
    time: '07:00',
    type: 'match',
    location: 'Parque Sarmiento, Córdoba',
    participants: ['ath_003'],
  },
  {
    id: 'evt_008',
    title: 'Reunión Cuerpo Técnico',
    description: 'Análisis del rival y planificación semanal',
    date: '2024-08-08',
    time: '08:00',
    type: 'meeting',
    location: 'Sala de video - Predio Racing',
    participants: ['coach_001', 'coach_004', 'hp_002'],
  },
];
