import { Convocatoria, MarketplaceCard } from '../core/models/marketplace.model';

export const MOCK_CONVOCATORIAS: Convocatoria[] = [
  {
    id: 'conv_001',
    publisherId: 'club_001',
    publisherName: 'Racing Club',
    publisherRole: 'institution',
    title: 'Preparador Físico para 5ta División',
    description: 'Buscamos Preparador Físico con experiencia en categorías juveniles de fútbol. Jornada completa de lunes a viernes. Disponibilidad para viajar a partidos de visitante.',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    type: 'job',
    requirements: ['Prof. Educación Física', '3+ años de experiencia en inferiores', 'Disponibilidad full-time'],
    budget: '$350.000 - $450.000 mensual',
    createdAt: '2024-08-01',
    status: 'open',
  },
  {
    id: 'conv_002',
    publisherId: 'club_002',
    publisherName: 'Club Atlético Vélez Sarsfield',
    publisherRole: 'institution',
    title: 'Prueba de Jugadores - Categoría 2008',
    description: 'Convocamos a jugadores nacidos en 2008 para prueba abierta en el predio de Villa Olímpica. Presentarse con ropa deportiva y DNI.',
    discipline: 'football',
    location: 'Liniers, Buenos Aires',
    type: 'tryout',
    requirements: ['Nacidos en 2008', 'Ficha médica actualizada', 'DNI'],
    createdAt: '2024-07-25',
    status: 'open',
  },
  {
    id: 'conv_003',
    publisherId: 'ath_003',
    publisherName: 'Matías Rodríguez',
    publisherRole: 'athlete',
    title: 'Busco sponsor técnico de indumentaria',
    description: 'Corredor de maratón con presencia en redes (15K seguidores). Busco marca de zapatillas/ropa para sponsoreo técnico. Corro 6 carreras al año.',
    discipline: 'running',
    location: 'Córdoba Capital, Córdoba',
    type: 'sponsor',
    requirements: ['Indumentaria de running', 'Zapatillas para competición y entrenamiento'],
    createdAt: '2024-07-30',
    status: 'open',
  },
  {
    id: 'conv_004',
    publisherId: 'club_003',
    publisherName: 'Jockey Club Rosario',
    publisherRole: 'institution',
    title: 'Kinesiólogo/a para plantel de hockey',
    description: 'Incorporamos kinesiólogo/a deportivo para atender al plantel de hockey femenino (Primera y Juveniles). 3 veces por semana.',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    type: 'job',
    requirements: ['Lic. en Kinesiología', 'Experiencia en deporte de equipo', 'Disponibilidad L-M-V'],
    budget: '$180.000 - $250.000 mensual',
    createdAt: '2024-08-03',
    status: 'open',
  },
  {
    id: 'conv_005',
    publisherId: 'ath_006',
    publisherName: 'Franco Díaz',
    publisherRole: 'athlete',
    title: 'Busco nutricionista para debut profesional',
    description: 'Boxeador peso mediano próximo a debutar como profesional. Necesito plan nutricional para dar el peso y rendir al máximo.',
    discipline: 'boxing',
    location: 'La Matanza, Buenos Aires',
    type: 'service',
    requirements: ['Experiencia en deportes de combate', 'Manejo de corte de peso'],
    budget: '$12.000 por consulta',
    createdAt: '2024-08-05',
    status: 'open',
  },
  {
    id: 'conv_006',
    publisherId: 'club_005',
    publisherName: 'Bahía Basket',
    publisherRole: 'institution',
    title: 'Videoanalista para Liga Femenina',
    description: 'Buscamos videoanalista part-time para el equipo femenino que compite en la Liga Nacional. Manejo de Synergy y edición de video.',
    discipline: 'basketball',
    location: 'Bahía Blanca, Buenos Aires',
    type: 'job',
    requirements: ['Manejo de Synergy Sports', 'Edición de video', 'Conocimiento táctico de básquet'],
    budget: '$150.000 - $200.000 mensual',
    createdAt: '2024-08-02',
    status: 'open',
  },
];

export const MOCK_MARKETPLACE_CARDS: MarketplaceCard[] = [
  {
    id: 'mc_001',
    userId: 'hp_001',
    fullName: 'Dra. Martina Pérez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Martina',
    role: 'health-professional',
    discipline: 'football',
    location: 'Caballito, Buenos Aires',
    rating: 4.8,
    reviewCount: 47,
    headline: 'Nutricionista deportiva - ISAK II',
    priceRange: '$8.000 - $15.000',
    tags: ['Nutrición deportiva', 'Antropometría', 'Suplementación'],
  },
  {
    id: 'mc_002',
    userId: 'hp_002',
    fullName: 'Roberto Silva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    role: 'health-professional',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    rating: 4.9,
    reviewCount: 62,
    headline: 'Preparador Físico - Alto Rendimiento',
    priceRange: '$10.000 - $20.000/mes',
    tags: ['Fuerza', 'Prevención', 'Readaptación'],
  },
  {
    id: 'mc_003',
    userId: 'hp_003',
    fullName: 'Lic. Alejandra García Méndez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandra',
    role: 'health-professional',
    discipline: 'running',
    location: 'Palermo, Buenos Aires',
    rating: 4.7,
    reviewCount: 35,
    headline: 'Kinesióloga - Lesiones deportivas',
    priceRange: '$6.000 - $12.000',
    tags: ['Rehabilitación', 'Punción seca', 'Running'],
  },
  {
    id: 'mc_004',
    userId: 'coach_001',
    fullName: 'Carlos Medina',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CarlosM',
    role: 'coach',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    rating: 4.6,
    reviewCount: 28,
    headline: 'DT - Formador de juveniles',
    tags: ['Inferiores', 'Táctica', 'Formación'],
  },
  {
    id: 'mc_005',
    userId: 'coach_002',
    fullName: 'María Sosa',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MariaSosa',
    role: 'coach',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    rating: 4.9,
    reviewCount: 41,
    headline: 'DT Hockey - Ex Leona',
    tags: ['Hockey femenino', 'Alto rendimiento', 'Formación'],
  },
  {
    id: 'mc_006',
    userId: 'ath_001',
    fullName: 'Lucas Martínez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    role: 'athlete',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    rating: 4.3,
    reviewCount: 12,
    headline: 'Mediocampista - Racing Reserva',
    tags: ['Fútbol', 'Mediocampista', 'Semi-pro'],
  },
  {
    id: 'mc_007',
    userId: 'hp_005',
    fullName: 'Lic. Carolina Romero',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carolina',
    role: 'health-professional',
    discipline: 'other',
    location: 'Belgrano, Buenos Aires',
    rating: 4.8,
    reviewCount: 53,
    headline: 'Psicóloga deportiva - Coaching mental',
    priceRange: '$7.000 - $12.000',
    tags: ['Psicología deportiva', 'Presión', 'Concentración'],
  },
  {
    id: 'mc_008',
    userId: 'ath_002',
    fullName: 'Sofía Gutiérrez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    role: 'athlete',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    rating: 4.5,
    reviewCount: 8,
    headline: 'Delantera - Selección Santa Fe Sub-21',
    tags: ['Hockey', 'Delantera', 'Profesional'],
  },
];
