import { Product } from '../core/models/product.model';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Botines Predator Elite FG',
    brand: 'Adidas',
    description: 'Botines de fútbol para campo natural con suela de tacos mixtos. Control total del balón con tecnología Controlskin.',
    price: 189999,
    originalPrice: 219999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=botines&backgroundColor=1a237e',
    category: 'footwear',
    discipline: 'football',
    rating: 4.7,
    reviewCount: 124,
    tags: ['Fútbol', 'Césped natural', 'Profesional'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod_002',
    name: 'Zapatillas Ultraboost Running',
    brand: 'Adidas',
    description: 'Zapatillas de running con amortiguación Boost para entrenamientos de larga distancia y maratones.',
    price: 159999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=running-shoes&backgroundColor=2e7d32',
    category: 'footwear',
    discipline: 'running',
    rating: 4.8,
    reviewCount: 231,
    tags: ['Running', 'Maratón', 'Amortiguación'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod_003',
    name: 'Proteína Whey Gold Standard 2lb',
    brand: 'Optimum Nutrition',
    description: '24g de proteína por scoop. Ideal para recuperación post-entrenamiento. Sabor doble chocolate.',
    price: 45999,
    originalPrice: 52999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=protein&backgroundColor=e65100',
    category: 'nutrition',
    discipline: 'all',
    rating: 4.9,
    reviewCount: 512,
    tags: ['Suplemento', 'Proteína', 'Recuperación'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod_004',
    name: 'Smartwatch Garmin Forerunner 265',
    brand: 'Garmin',
    description: 'Reloj GPS con métricas avanzadas de running, VO2Max, planes de entrenamiento y monitor de frecuencia cardíaca.',
    price: 389999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=garmin&backgroundColor=00838f',
    category: 'technology',
    discipline: 'running',
    rating: 4.8,
    reviewCount: 89,
    tags: ['GPS', 'Running', 'Métricas'],
    inStock: true,
  },
  {
    id: 'prod_005',
    name: 'Pelota de Fútbol FIFA Quality Pro',
    brand: 'Nike',
    description: 'Pelota de competición certificada FIFA. Construcción termosellada para vuelo estable y toque preciso.',
    price: 69999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=pelota&backgroundColor=6a1b9a',
    category: 'equipment',
    discipline: 'football',
    rating: 4.6,
    reviewCount: 67,
    tags: ['Fútbol', 'Competición', 'FIFA'],
    inStock: true,
  },
  {
    id: 'prod_006',
    name: 'Palo de Hockey Grays GR9000',
    brand: 'Grays',
    description: 'Palo de hockey de competición. 90% carbono, perfil extra low bow para drag flicks y controles en velocidad.',
    price: 249999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=hockey-stick&backgroundColor=c62828',
    category: 'equipment',
    discipline: 'hockey',
    rating: 4.5,
    reviewCount: 34,
    tags: ['Hockey', 'Carbono', 'Competición'],
    inStock: true,
  },
  {
    id: 'prod_007',
    name: 'Camiseta térmica compresión',
    brand: 'Under Armour',
    description: 'Camiseta de compresión manga larga. Tecnología HeatGear para mantener el cuerpo fresco y seco.',
    price: 34999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=camiseta&backgroundColor=1565c0',
    category: 'apparel',
    discipline: 'all',
    rating: 4.4,
    reviewCount: 156,
    tags: ['Compresión', 'Entrenamiento', 'Térmica'],
    inStock: true,
  },
  {
    id: 'prod_008',
    name: 'Guantes de Boxeo 12oz',
    brand: 'Everlast',
    description: 'Guantes de entrenamiento y sparring. Acolchado de espuma de alta densidad. Cierre velcro.',
    price: 54999,
    originalPrice: 64999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=boxing-gloves&backgroundColor=d32f2f',
    category: 'equipment',
    discipline: 'boxing',
    rating: 4.3,
    reviewCount: 78,
    tags: ['Boxeo', 'Sparring', 'Entrenamiento'],
    inStock: true,
  },
  {
    id: 'prod_009',
    name: 'Banda elástica set x5 resistencias',
    brand: 'TheraBand',
    description: 'Set de 5 bandas elásticas con diferentes resistencias. Ideal para rehabilitación, calentamiento y activación.',
    price: 12999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=bands&backgroundColor=ff6d00',
    category: 'accessories',
    discipline: 'all',
    rating: 4.6,
    reviewCount: 203,
    tags: ['Rehabilitación', 'Calentamiento', 'Funcional'],
    inStock: true,
  },
  {
    id: 'prod_010',
    name: 'Creatina monohidrato 300g',
    brand: 'ENA Sport',
    description: 'Creatina pura micronizada. Mejora fuerza, potencia y rendimiento en entrenamientos de alta intensidad.',
    price: 18999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=creatina&backgroundColor=4527a0',
    category: 'nutrition',
    discipline: 'all',
    rating: 4.7,
    reviewCount: 145,
    tags: ['Suplemento', 'Fuerza', 'Rendimiento'],
    inStock: true,
  },
  {
    id: 'prod_011',
    name: 'Mochila deportiva 40L',
    brand: 'Nike',
    description: 'Mochila con compartimiento para botines, bolsillo para pelota y porta botella. Espalda acolchada.',
    price: 44999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=mochila&backgroundColor=37474f',
    category: 'accessories',
    discipline: 'all',
    rating: 4.5,
    reviewCount: 92,
    tags: ['Mochila', 'Entrenamiento', 'Transporte'],
    inStock: true,
  },
  {
    id: 'prod_012',
    name: 'Canilleras Pro con tobillera',
    brand: 'Nike',
    description: 'Canilleras livianas con protección reforzada y tobillera integrada. Ajuste anatómico.',
    price: 29999,
    originalPrice: 34999,
    image: 'https://api.dicebear.com/7.x/shapes/svg?seed=canilleras&backgroundColor=0d47a1',
    category: 'equipment',
    discipline: 'football',
    rating: 4.4,
    reviewCount: 56,
    tags: ['Fútbol', 'Protección', 'Canilleras'],
    inStock: false,
  },
];
