import { HealthProfessionalProfile, CoachProfile } from '../core/models/user.model';

export const MOCK_HEALTH_PROFESSIONALS: HealthProfessionalProfile[] = [
  {
    id: 'hp_001',
    email: 'dra.martinaperez@mail.com',
    fullName: 'Dra. Martina Pérez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Martina',
    role: 'health-professional',
    discipline: 'football',
    location: 'Caballito, Buenos Aires',
    bio: 'Nutricionista deportiva con 8 años de experiencia en clubes de primera división. Especialista en periodización nutricional.',
    createdAt: new Date('2023-11-20'),
    specialtyType: 'nutritionist',
    certifications: ['Lic. en Nutrición (UBA)', 'ISAK Nivel II', 'Posgrado Nutrición Deportiva'],
    servicesOffered: ['Planes nutricionales', 'Antropometría', 'Suplementación deportiva', 'Control de peso'],
    priceRange: '$8.000 - $15.000 por consulta',
  },
  {
    id: 'hp_002',
    email: 'roberto.silva@mail.com',
    fullName: 'Roberto Silva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto',
    role: 'health-professional',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    bio: 'Preparador Físico con experiencia en divisiones inferiores y primera de Racing Club. Enfoque en prevención de lesiones.',
    createdAt: new Date('2023-09-15'),
    specialtyType: 'physical-trainer',
    certifications: ['Prof. Educación Física (UNLP)', 'Esp. Alto Rendimiento', 'FMS Certified'],
    servicesOffered: ['Preparación física', 'Prevención de lesiones', 'Readaptación', 'Planes de fuerza'],
    priceRange: '$10.000 - $20.000 mensual',
  },
  {
    id: 'hp_003',
    email: 'lic.garciamendez@mail.com',
    fullName: 'Lic. Alejandra García Méndez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandra',
    role: 'health-professional',
    discipline: 'running',
    location: 'Palermo, Buenos Aires',
    bio: 'Kinesióloga especializada en lesiones deportivas. Trabajo con corredores y triatletas.',
    createdAt: new Date('2024-01-05'),
    specialtyType: 'kinesiologist',
    certifications: ['Lic. Kinesiología (UBA)', 'Dry Needling', 'RPG', 'Kinesiotaping'],
    servicesOffered: ['Rehabilitación deportiva', 'Terapia manual', 'Punción seca', 'Reeducación postural'],
    priceRange: '$6.000 - $12.000 por sesión',
  },
  {
    id: 'hp_004',
    email: 'dr.gonzalez@mail.com',
    fullName: 'Dr. Hernán González',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hernan',
    role: 'health-professional',
    discipline: 'football',
    location: 'La Plata, Buenos Aires',
    bio: 'Médico deportólogo. Atiendo jugadores de Estudiantes y Gimnasia. Apto físico y seguimiento de lesiones.',
    createdAt: new Date('2023-08-10'),
    specialtyType: 'sports-doctor',
    certifications: ['Médico (UNLP)', 'Esp. Medicina del Deporte', 'Ecografía MSK'],
    servicesOffered: ['Apto físico', 'Ecografía deportiva', 'Infiltraciones', 'Seguimiento de lesiones'],
    priceRange: '$10.000 - $25.000 por consulta',
  },
  {
    id: 'hp_005',
    email: 'lic.psico.romero@mail.com',
    fullName: 'Lic. Carolina Romero',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carolina',
    role: 'health-professional',
    discipline: 'other',
    location: 'Belgrano, Buenos Aires',
    bio: 'Psicóloga deportiva. Trabajo con la presión competitiva, concentración y manejo de lesiones desde lo mental.',
    createdAt: new Date('2024-02-14'),
    specialtyType: 'psychologist',
    certifications: ['Lic. Psicología (UBA)', 'Posgrado Psicología del Deporte', 'Coaching Deportivo'],
    servicesOffered: ['Preparación mental', 'Manejo de presión', 'Visualización', 'Coaching grupal'],
    priceRange: '$7.000 - $12.000 por sesión',
  },
];

export const MOCK_COACHES: CoachProfile[] = [
  {
    id: 'coach_001',
    email: 'carlos.medina@mail.com',
    fullName: 'Carlos Medina',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CarlosM',
    role: 'coach',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    bio: 'Director Técnico con 15 años de experiencia en divisiones inferiores. Formador de jugadores para primera división.',
    createdAt: new Date('2023-06-20'),
    coachType: 'head-coach',
    currentTeam: 'Racing Club - 5ta División',
    experience: '15 años en inferiores de Racing y Defensa y Justicia',
    certifications: ['DT Nacional (AFA)', 'Licencia UEFA B', 'Análisis táctico avanzado'],
  },
  {
    id: 'coach_002',
    email: 'maria.sosa@mail.com',
    fullName: 'María Sosa',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MariaSosa',
    role: 'coach',
    discipline: 'hockey',
    location: 'Rosario, Santa Fe',
    bio: 'Entrenadora de hockey femenino. Ex-jugadora de Las Leonas. Trabajo en formación de jugadoras jóvenes.',
    createdAt: new Date('2024-01-15'),
    coachType: 'head-coach',
    currentTeam: 'Jockey Club Rosario - Primera',
    experience: '8 años como DT, 12 años como jugadora profesional',
    certifications: ['DT Nacional Hockey', 'FIH Academy Level 2'],
  },
  {
    id: 'coach_003',
    email: 'pablo.ruiz@mail.com',
    fullName: 'Pablo Ruiz',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PabloR',
    role: 'coach',
    discipline: 'football',
    location: 'Liniers, Buenos Aires',
    bio: 'Videoanalista con manejo de software de análisis táctico. Trabajo en Vélez Sarsfield.',
    createdAt: new Date('2024-03-01'),
    coachType: 'video-analyst',
    currentTeam: 'Club Atlético Vélez Sarsfield - Primera',
    experience: '6 años de videoanalisis en clubes de primera',
    certifications: ['Analista de rendimiento (ATFA)', 'InStat certificado', 'Wyscout Pro'],
  },
  {
    id: 'coach_004',
    email: 'diego.torres@mail.com',
    fullName: 'Diego Torres',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DiegoT',
    role: 'coach',
    discipline: 'football',
    location: 'Avellaneda, Buenos Aires',
    bio: 'Entrenador de arqueros. Trabajo con todas las categorías de Racing Club.',
    createdAt: new Date('2023-10-05'),
    coachType: 'goalkeeper-coach',
    currentTeam: 'Racing Club - Todas las categorías',
    experience: '10 años como entrenador de arqueros',
    certifications: ['DT Nacional (AFA)', 'Especialización Arco (AFA)'],
  },
];
