import { StaffRecommendation } from '../core/models/club.model';

export const MOCK_RECOMMENDATIONS: StaffRecommendation[] = [
  // Recommendations for Lucas Martínez (ath_001)
  {
    id: 'rec_001',
    playerId: 'ath_001',
    staffId: 'hp_001',
    staffName: 'Dra. Martina Pérez',
    staffRole: 'Nutricionista',
    type: 'diet',
    title: 'Plan Nutricional - Semana de Competencia',
    description: 'Ajuste calórico para semana con doble competencia. Priorizar hidratación y carga de glucógeno.',
    details: [
      'Desayuno: Avena con banana, miel y frutos secos + jugo natural',
      'Media mañana: Tostadas integrales con palta y huevo',
      'Almuerzo: Pollo grillado con arroz integral y verduras salteadas',
      'Merienda pre-entreno: Barrita energética + banana',
      'Post-entreno: Batido proteico con leche y avena',
      'Cena: Pasta con salsa bolognesa magra + ensalada',
      'Hidratación: 3-4 litros diarios, bebida isotónica en entrenamiento',
    ],
    createdAt: '2024-08-01',
    status: 'active',
  },
  {
    id: 'rec_002',
    playerId: 'ath_001',
    staffId: 'hp_002',
    staffName: 'Roberto Silva',
    staffRole: 'Preparador Físico',
    type: 'exercise',
    title: 'Rutina de Fuerza - Tren Inferior',
    description: 'Sesión de fuerza orientada a potencia de piernas y prevención de isquiotibiales.',
    details: [
      'Entrada en calor: 10min bicicleta + movilidad articular',
      'Sentadillas: 4x6 al 80% RM',
      'Peso muerto rumano: 3x8 con foco en excéntrica',
      'Prensa 45°: 3x10',
      'Nordic hamstring: 3x5',
      'Step-ups con mancuerna: 3x8 por pierna',
      'Core: Plancha 3x45seg + rotaciones con polea 3x12',
      'Vuelta a la calma: Elongación 10min',
    ],
    createdAt: '2024-08-02',
    status: 'active',
  },
  {
    id: 'rec_003',
    playerId: 'ath_001',
    staffId: 'coach_001',
    staffName: 'Carlos Medina',
    staffRole: 'Director Técnico',
    type: 'tactical',
    title: 'Indicaciones Tácticas - Partido vs Independiente',
    description: 'Rol como mediocampista interno con libertad para pisar el área rival.',
    details: [
      'Posición base: Interno derecho en 4-3-3',
      'Con pelota: buscar asociación con el extremo, pisar el área en segunda jugada',
      'Sin pelota: cerrar línea de pase al volante rival, pressing alto',
      'Pelota parada: marca en zona central del área',
      'Transición ofensiva: buscar el espacio entre líneas',
    ],
    createdAt: '2024-08-03',
    status: 'active',
  },
  // Recommendations for Sofía Gutiérrez (ath_002)
  {
    id: 'rec_004',
    playerId: 'ath_002',
    staffId: 'hp_003',
    staffName: 'Lic. Alejandra García Méndez',
    staffRole: 'Kinesióloga',
    type: 'rehabilitation',
    title: 'Protocolo de Prevención - Rodilla',
    description: 'Ejercicios de estabilización de rodilla post sobrecarga en entrenamiento.',
    details: [
      'Isométricos de cuádriceps: 4x30seg',
      'Sentadilla isométrica en pared: 3x45seg',
      'Equilibrio unipodal en superficie inestable: 3x30seg por lado',
      'Puente glúteo con banda: 3x15',
      'Aplicar hielo 15min post actividad',
      'Próximo control: jueves 8/8',
    ],
    createdAt: '2024-08-01',
    status: 'active',
  },
  {
    id: 'rec_005',
    playerId: 'ath_002',
    staffId: 'coach_002',
    staffName: 'María Sosa',
    staffRole: 'Directora Técnica',
    type: 'tactical',
    title: 'Trabajo Individual - Definición',
    description: 'Ejercicios específicos de definición dentro del área chica para mejorar efectividad.',
    details: [
      'Lunes: Definición de revés después de recibir centro (20 repeticiones)',
      'Miércoles: Push con variantes de ángulo (15 repeticiones)',
      'Viernes: Situaciones de 1v1 con arquera + definición rápida',
      'Video: revisar goles de Delfina Merino para inspiración táctica',
    ],
    createdAt: '2024-07-28',
    status: 'active',
  },
  // Recommendations for Nicolás Fernández (ath_005)
  {
    id: 'rec_006',
    playerId: 'ath_005',
    staffId: 'hp_001',
    staffName: 'Dra. Martina Pérez',
    staffRole: 'Nutricionista',
    type: 'diet',
    title: 'Plan Nutricional - Recuperación Muscular',
    description: 'Nutrición enfocada en recuperación post-partido con doble jornada.',
    details: [
      'Post-partido inmediato: Batido recovery (proteína + carbohidrato)',
      'Cena post-partido: Salmón con batata y vegetales verdes',
      'Día siguiente: Aumentar proteína a 2.2g/kg peso corporal',
      'Suplementar con omega-3 y magnesio antes de dormir',
      'Hidratación reforzada con electrolitos',
    ],
    createdAt: '2024-08-04',
    status: 'active',
  },
  {
    id: 'rec_007',
    playerId: 'ath_005',
    staffId: 'hp_002',
    staffName: 'Roberto Silva',
    staffRole: 'Preparador Físico',
    type: 'exercise',
    title: 'Sesión Regenerativa - Día Post Partido',
    description: 'Sesión liviana para favorecer la recuperación muscular.',
    details: [
      'Bicicleta suave: 15min a baja intensidad',
      'Foam roller: 10min en isquiotibiales, cuádriceps, gemelos',
      'Movilidad articular: caderas, tobillos, columna (5min)',
      'Elongación estática suave: 10min',
      'Pileta: 15min de trote acuático si hay disponible',
    ],
    createdAt: '2024-08-04',
    status: 'active',
  },
];
